export const SET_DECODED_DOMAINS_START = 'SET_DECODED_DOMAINS_START';
export const SET_DECODED_DOMAINS_SUCCESS = 'SET_DECODED_DOMAINS_SUCCESS';
export const SET_DECODED_DOMAINS_FAIL = 'SET_DECODED_DOMAINS_FAIL';

export const UPDATE_DECODE_DOMAINS_ALL = 'UPDATE_DECODE_DOMAINS_ALL';
export const UPDATE_DECODE_DOMAINS_ITEM = 'UPDATE_DECODE_DOMAINS_ITEM';

export const CLEAR_DECODED_DOMAINS = 'CLEAR_DECODED_DOMAINS';

export const CHECK_CONNECTION_START = 'CHECK_CONNECTION_START';
export const CHECK_CONNECTION_SUCCESS = 'CHECK_CONNECTION_SUCCESS';
export const CHECK_CONNECTION_FAIL = 'CHECK_CONNECTION_FAIL';

export const HISTORY_DOMAINS_SAVE_HISTORY = 'HISTORY_DOMAINS_SAVE_HISTORY';
export const HISTORY_DOMAINS_LOAD_HISTORY = 'HISTORY_DOMAINS_LOAD_HISTORY';
export const HISTORY_DOMAINS_REMOVE_HISTORY = 'HISTORY_DOMAINS_REMOVE_HISTORY';
export const HISTORY_DOMAINS_SORT_FILTER_SUCCESS =
  'HISTORY_DOMAINS_SORT_FILTER_SUCCESS';
export const HISTORY_DOMAINS_SORT_FILTER_FAIL =
  'HISTORY_DOMAINS_SORT_FILTER_FAIL';
export const HISTORY_DOMAINS_SORT_FILTER_ALL =
  'HISTORY_DOMAINS_SORT_FILTER_ALL';
export const HISTORY_DOMAINS_SET_FILTERED = 'HISTORY_DOMAINS_SET_FILTERED';
export const HISTORY_DOMAINS_RESET_FILTER = 'HISTORY_DOMAINS_RESET_FILTER';
