export const SET_DECODED_DOMAINS_START = 'SET_DECODED_DOMAINS_START';
export const SET_DECODED_DOMAINS_SUCCESS = 'SET_DECODED_DOMAINS_SUCCESS';
export const SET_DECODED_DOMAINS_FAIL = 'SET_DECODED_DOMAINS_FAIL';

export const UPDATE_DECODE_DOMAINS_ALL = 'UPDATE_DECODE_DOMAINS_ALL';
export const UPDATE_DECODE_DOMAINS_ITEM = 'UPDATE_DECODE_DOMAINS_ITEM';

export const CLEAR_DECODED_DOMAINS = 'CLEAR_DECODED_DOMAINS';

export const SAVE_DOMAINS_TO_HISTORY = 'SAVE_DOMAINS_TO_HISTORY';
